version: '3.9'
services:
  backend:
    container_name: bid-backend-server
    image: vuhoangdung/web-bid-backend:latest
    depends_on:
      - postgre
    env_file: .env
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5432
    networks:
      - web-bid-network

  frontend:
    container_name: bid-frontend-server
    image: vuhoangdung/web-bid-frontend:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - web-bid-network
 #
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/log:/var/log/nginx
      - ./certbot/certs/cert.pem:/etc/letsencrypt/live/auctionforfun.site/fullchain.pem:ro
      - ./certbot/privkeys/key.pem:/etc/letsencrypt/live/auctionforfun.site/privkey.pem:ro
      - ./certbot/dhparam/dhparam.pem:/etc/ssl/certs/dhparam-2048.pem
      - /var/run/docker.sock:/tmp/docker.sock:ro
    tty: true
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - web-bid-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/certs/cert.pem:/etc/letsencrypt/live/auctionforfun.site/fullchain.pem:ro
      - ./certbot/privkeys/key.pem:/etc/letsencrypt/live/auctionforfun.site/privkey.pem:ro
      - ./certbot/dhparam/dhparam.pem:/etc/ssl/certs/dhparam-2048.pem
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx
    command: >-
        certonly --email vhngdng@gmail.com --agree-tos --no-eff-email --webroot -w /var/www/html --cert-name auctionforfun.site -d auctionforfun.site,www.auctionforfun.site
      # - certbot --webroot -w /var/www/html renew --email vhngdng@gmail.com \
      #   --agree-tos --no-eff-email --staging \
      #   run --force-renewal --cert-name auctionforfun.site --nginx -d www.auctionforfun.site,auctionforfun.site
      # - certbot certonly reconfigure --pre-hook 'service nginx stop' --post-hook 'service nginx start' \
      #   --deploy-hook "docker kill -s HUP nginx" -n --cert-name auctionforfun.site \
      #   -d www.auctionforfun.site,auctionforfun.site
    networks:
      - web-bid-network
    
  postgre:
    image: postgres:15.2
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=web-project
    volumes:
      - ./dbdata:/var/lib/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - web-bid-network

networks:
  web-bid-network:
    driver: bridge

