version: '3.9'
services:
  backend:
    container_name: bid-backend-server
    image: vuhoangdung/web-bid-backend:latest
    depends_on:
      - postgre
    env_file: .env
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5432
    networks:
      - web-bid-network

  frontend:
    container_name: bid-frontend-server
    image: vuhoangdung/web-bid-frontend:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - web-bid-network
 #
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    networks:
      - web-bid-network
    tty: true
    depends_on:
      - frontend
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/tmp/letsencrypt:rw
      - ./certbot/letsencrypt:/etc/letsencrypt:rw
    command: 
      certonly --webroot --agree-tos --renew-by-default \
      --preferred-challenges http-01 --server https://acme-v02.api.letsencrypt.org/directory \
      --text --email vhngdng@gmail.com \
      -w /tmp/letsencrypt -d auctionforfun.site 
    
      # certonly
      # --cert-name auctionforfun.site
      # --server https://acme-v02.api.letsencrypt.org/directory \
      # --nginx \
      # --dns-digitalocean \
      # --dns-digitalocean-credentials ~/.secrets/certbot/digitalocean.ini \
      # -d auctionforfun.site \
      # -d www.auctionforfun.site
    networks:
      - web-bid-network

  postgre:
    image: postgres:15.2
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=web-project
    volumes:
      - ./dbdata:/var/lib/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - web-bid-network

networks:
  web-bid-network:
    driver: bridge

