name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - "backend/demo/spring-resource-server/**"
      - "front-end/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create env file for backend
        run: |
          echo "${SPRINGBOOTENV}" > ./backend/demo/spring-resource-server/src/main/resources/.env
          echo "${FRONTEND_ENV}" > ./front-end/.env.development.local
          echo "${DOCKERCOMPOSE_ENV}" > ./.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${ secrets.DOCKERHUB_USERNAME }
          password: ${ secrets.DOCKERHUB_TOKEN }

      - name: Test docker username and password
        run: |
          echo ${ secrets.DOCKERHUB_USERNAME }
          echo ${ secrets.DOCKERHUB_TOKEN }

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vuhoangdung/web-bid:${TAG_NAME}

  # deploy:
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout files
  #       uses: actions/checkout@v3

  #     - name: Get Tag name
  #       uses: vuhoangdung/

  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #       token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
