name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - "backend/demo/spring-resource-server/**"
      - "front-end/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create env file for backend
        run: |
          echo ".env=${{ secrets.SPRINGBOOTENV }}" > ./backend/demo/spring-resource-server/src/main/resources/.env
          echo ".env.development.local=${{ secrets.FRONTEND_ENV }}" > ./front-end/.env.development.local
          echo ".env=${{ secrets.DOCKERCOMPOSE_ENV }}" > ./.env

      - name: Test docker username and password
        run: |
          echo "${{ secrets.DOCKERHUB_USERNAME }}"
          echo "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            vuhoangdung/bid-backend-server:${{secrets.TAG_NAME}}
            vuhoangdung/bid-frontend-server:${{secrets.TAG_NAME}}
          dockerfile: |
            ./backend/demo/spring-resource-server
            ./front-end

  # deploy:
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout files
  #       uses: actions/checkout@v3

  #     - name: Get Tag name
  #       uses: vuhoangdung/

  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #       token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
