name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - "backend/demo/spring-resource-server/**"
      - "front-end/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create env file for backend
        run: |
          echo ".env=${{ secrets.SPRINGBOOTENV }}" > ./backend/demo/spring-resource-server/src/main/resources/.env
          echo ".env.development.local=${{ secrets.FRONTEND_ENV }}" > ./front-end/.env.development.local
          echo ".env=${{ secrets.DOCKERCOMPOSE_ENV }}" > ./.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Backend Build and push Docker
        uses: docker/build-push-action@v4
        with:
          context: |
            backend/demo/spring-resource-server
          push: true
          tags: |
            vuhoangdung/web-bid:bid-backend-server
          dockerfile: Dockerfile

      - name: Frontend Build and push Docker
        uses: docker/build-push-action@v4
        with:
          context: front-end
          push: true
          tags: |
            vuhoangdung/web-bid:bid-frontend-server
          dockerfile: Dockerfile

  deploy:
    needs: build

    env:
      DIGITALOCEAN_DROPLET_IP: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
      USER: ${{ secrets.USER_SERVER }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      # - name: Start SSH agent
      #   uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "ssh-keyscan -H ${{ secrets.DIGITALOCEAN_DROPLET_IP }}" > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_SERVER }}@${{ secrets.DIGITALOCEAN_DROPLET_IP }} "scp ~/Documents/web/deploy.sh $USER@$DIGITALOCEAN_DROPLET_IP:./deploy.sh"
          chmod +x ./deploy.sh
          ./deploy.sh

      - name: cleanup
        run: rm -rf ~/.ssh
